icons_format = "{icon}"

#[theme]
##theme = "gruvbox-dark"
#[theme.overrides]
##info_bg = "#282828"
##info_fg = "#ebdbb2"
##good_bg = "#282828"
##good_fg = "#ebdbb2"

[icons]
icons = "/home/tulimiero/Repos/i3status-rust/files/icons/awesome6.toml"
[icons.overrides]
volume_muted = "\uf026 \uf00d"
backlight = [
    "\uf0eb",
    "\uf0eb",
    "\uf0eb",
    "\uf0eb",
    "\uf0eb",
]

# Music {{{
[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20)|} "
# }}}

# Networks {{{
[[block]]
block = "net"
format = " $icon {$ssid $frequency|Wired connection} "
# }}}

# Disk {{{
[[block]]
block = "disk_space"
info_type = "available"
path = "/home"
alert_unit = "GB"
alert = 10.0
warning = 20.0
# }}}

# Memory {{{
[[block]]
block = "memory"
interval = 30
format = " $icon $mem_used_percents.eng(w:1) "
warning_mem = 90
critical_mem = 99
# }}}

# Light {{{
[[block]]
block = "backlight"
# }}}

# Battery {{{
[[block]]
block = "battery"
interval = 10
format = " $icon $percentage "
full_threshold = 99
info = 99
critical = 10
# }}}

# Sound {{{
[[block]]
block = "sound"
# }}}

# Time & Date {{{
[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%a %d/%m %R') "
# }}}
