[theme]
name = "gruvbox-dark"
[theme.overrides]
info_bg = "#282828"
info_fg = "#ebdbb2"
good_bg = "#282828"
good_fg = "#ebdbb2"

[icons]
name = "awesome"
[icons.overrides]
memory_mem = " "
cpu = " "
bat_charging = " "

# [[block]]
# block = "focused_window"
# max_width = 25

# Music {{{
[[block]]
block = "music"
buttons = ["play", "next"]
on_collapsed_click = "spotify"
marquee = false
smart_trim = true
# }}}

# Networks {{{
[[block]]
block = "net"
device = "enp0s20f0u3"
interval = 10
hide_missing = true
hide_inactive = true

[[block]]
block = "net"
device = "enp0s20f0u4"
interval = 10
hide_missing = true
hide_inactive = true

[[block]]
block = "net"
device = "wlp0s20f3"
interval = 10
hide_missing = true
hide_inactive = true
# }}}

# Disk {{{
[[block]]
block = "disk_space"
path = "/home"
alias = ""
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
# }}}

# Memory {{{
[[block]]
block = "memory"
display_type = "memory"
clickable = false
warning_mem = 90
# }}}

# Light {{{
[[block]]
block = "backlight"
# }}}

# Battery {{{
[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"
# }}}

# Sound {{{
[[block]]
block = "sound"
# }}}

# Time & Date {{{
[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
# }}}
